services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-gow-vanilla
    user: "0:0"
    ports:
      - "1217:1217"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "VANILLA"
      VERSION: "1.21.7"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "8G"
      SERVER_PORT: "1217"
      DIFFICULTY: "hard"
      AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: "3600"
      AUTOPAUSE_TIMEOUT_KN: "120"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "GOW Vanilla"
      MOTD: "Server oficial da \u00A7eGOW \u00A77no minecraft"
      ICON: "/data/server-icon.png"
      OVERRIDE_ICON: "TRUE"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "gow123"
      RCON_PORT: "12171"
      REMOVE_OLD_MODS: "false"
      SYNC_SKIP_NEWER_FILES: "false"
      USE_AIKAR_FLAGS: "TRUE"
      BACKUP_ON_START: "TRUE"
      ENABLE_QUERY: "TRUE"
      QUERY_PORT: "1217"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "8"
      MAX_PLAYERS: "20"
      PVP: "TRUE"
      SPAWN_ANIMALS: "TRUE"
      SPAWN_MONSTERS: "TRUE"
      SPAWN_NPCS: "TRUE"
      FORCE_GAMEMODE: "FALSE"
      GAMEMODE: "survival"
      BROADCAST_RCON_TO_OPS: "TRUE"
      BROADCAST_CONSOLE_TO_OPS: "TRUE"
    volumes:
      - gow_vanilla_data:/data
      - ./server-icon.png:/data/server-icon.png:ro
      - ./Gow:/data/world
    stdin_open: true
    tty: true
volumes:
  gow_vanilla_data: {} 