services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-forge-back_on_track
    ports:
      - "1182:1182"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.18.2"
      FORGEVERSION: "40.2.9"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "12G"
      SERVER_PORT: "1182"
      REMOVE_OLD_MODS: "true"
      DIFFICULTY: "hard"
      AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: "3600"
      AUTOPAUSE_TIMEOUT_KN: "120"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "Carimbo create back on track"
      MOTD:    Server oficial dos \u00A74\u00A7lcarimbos \u00A7lDOFAL \u00A76\u00A7lback on track
      ICON: "/data/server-icon.png"
      OVERRIDE_ICON: "TRUE"
    volumes:
      - minecraft-forge-back_on_track:/data
      - ./mods:/mods:ro
      - ./config:/config:ro
      - ./defaultconfigs:/data/defaultconfigs:ro
      - ./kubejs:/data/kubejs:ro
      - ./server-icon.png:/data/server-icon.png:ro
    stdin_open: true
    tty: true
volumes:
  minecraft-forge-back_on_track: {}