services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-forge-carimbo-1.20
    ports:
      - "1201:1201"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGEVERSION: "47.3.22"
      MEMORY: "8G"
      SERVER_PORT: "1201"
      REMOVE_OLD_MODS: "true"
      # DEBUG: "true"
    volumes:
      - mc_forge_carimbo_1.20:/data
      - ./mods:/mods:ro
      - ./config:/config:ro
      - ./defaultconfigs:/data/defaultconfigs:ro
    stdin_open: true
    tty: true
volumes:
  mc_forge_carimbo_1.20: {}