services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-forge-carimbo-1.20
    ports:
      - "1201:1201"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGEVERSION: "47.3.22"
      MEMORY: "8G"
      SERVER_PORT: "1201"
      REMOVE_OLD_MODS: "true"
      AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: "3600"
      AUTOPAUSE_TIMEOUT_KN: "120"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "Carimbo 1.20.1"
      MOTD:    Server oficial dos \u00A74\u00A7lcarimbos \u00A7lDOFAL \u00A76\u00A7l1.201
      ICON: "/data/server-icon.png"
      OVERRIDE_ICON: "TRUE"
    volumes:
      - mc_forge_carimbo_1.20:/data
      # - ./mods:/mods:ro
      # - ./config:/config:ro
      # - ./defaultconfigs:/data/defaultconfigs:ro
      - ./server-icon.png:/data/server-icon.png:ro
    stdin_open: true
    tty: true
volumes:
  mc_forge_carimbo_1.20: {}