name: STOP SERVER carimbo 1.20.1

on:
  workflow_dispatch:

jobs:
  stop-server:
    runs-on: mc-server-runner

    steps:

      - name: Desligar container com servidor
        run: |
          cd $GITHUB_WORKSPACE/carimbo1201 && \
          docker compose down