name: Deploy carimbo 1.19.2

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: mc-server-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          cd $GITHUB_WORKSPACE/carimbo119 && \
          docker compose down && \
          docker compose up -d
  
  observe:
    runs-on: mc-server-runner
    needs:  deploy
    steps:
      - name: Observe os logs até que o servidor esteja no ar
        run: |
          cd $GITHUB_WORKSPACE/carimbo119 && \
          timeout 300 sh -c 'docker compose logs -f | tee /dev/tty | grep -q "Dedicated server took"' && \
          echo "Servidor no ar!" || (echo "Timeout atingido: Servidor não está no ar." && exit 1)