name: START SERVER carimbo 1.20.1

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: mc-server-runner

    steps:

      - name: Iniciar container com servidor
        run: |
          cd $GITHUB_WORKSPACE/carimbo1201 && \
          docker compose up -d

  observe:
    runs-on: mc-server-runner
    needs:  start-server
    steps:
      - name: Observe os logs até que o servidor esteja no ar
        run: |
          cd $GITHUB_WORKSPACE/carimbo1201 && \
          timeout 300 sh -c 'docker compose logs -f | tee /dev/tty | grep -q "Dedicated server took"' && \
          echo "Servidor no ar!" || (echo "Timeout atingido: Servidor não está no ar." && exit 1)