name: Deploy carimbo 1.19.2

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: mc-server-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          cd $GITHUB_WORKSPACE/carimbo119 && \
          docker compose down && \
          docker compose up -d
  
  observe:
    runs-on: mc-server-runner
    needs:  deploy
    steps:
      - name: Observe os logs por 5 minutos
        run: |
          cd $GITHUB_WORKSPACE/carimbo119 && \
          docker compose logs -f &
          sleep 300