name: Deploy carimbo back on track

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: mc-server-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          cd $GITHUB_WORKSPACE/back_on_track && \
          docker compose down && \
          docker compose up -d

  observe:
    runs-on: mc-server-runner
    needs:  deploy
    steps:
      - name: Observe os logs até que o servidor esteja no ar
        run: |
          cd $GITHUB_WORKSPACE/back_on_track && \
          timeout 300 sh -c 'docker compose logs -f | while IFS= read -r line; do
            echo "$line"; 
            if echo "$line" | grep -q "Dedicated server took"; then 
              echo "Servidor no ar!"; 
              exit 0; 
            fi; 
          done' || (echo "Timeout atingido: Servidor não está no ar." && exit 1)