name: START SERVER carimbo 1.19.2

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: mc-server-runner

    steps:

      - name: Iniciar container com servidor
        run: |
          cd $GITHUB_WORKSPACE/carimbo119 && \
          docker compose up -d
  
  observe:
    runs-on: mc-server-runner
    needs:  start-server
    steps:
      - name: Observe os logs até que o servidor esteja no ar
        run: |
          cd $GITHUB_WORKSPACE/carimbo119 && \
          (docker compose logs -f | tee /dev/tty | grep -q "Dedicated server took" && echo "Servidor no ar!")